import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers/provider";
import { HeroUIProvider } from "@heroui/react";
import NavbarDLV from "@/components/NavbarDLV";
import Footer from "@/components/Footer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body >
        <Providers>
         <div  className="min-h-screen flex flex-col">
            <NavbarDLV />
            <main className="flex-1">
              {children}
            </main>
            <Footer/>
          </div>
        </Providers>
      </body>
    </html>
  );
}
